apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloworld-api
  name: helloworld-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld-api
    spec:
      containers:
      - image: sreesanpd/helloworld-api:latest
        name: helloworld-api
        resources: {}
status: {}
